"""Pydantic data models for the AI Debugging Agent."""

from typing import List, Optional
from pydantic import BaseModel, Field


class ErrorContext(BaseModel):
    """Structured representation of a parsed Python error."""

    error_type: str = Field(
        description="Python exception class name, e.g. 'TypeError'"
    )
    error_message: str = Field(
        description="The error message text after the colon"
    )
    line_number: int = Field(
        description="Line number where the error occurred (0 if unknown)"
    )
    file_name: str = Field(
        description="Source file name from traceback (or 'unknown')"
    )
    code_lines: List[str] = Field(
        default_factory=list,
        description="Lines +-5 around the error line from the code snippet",
    )
    full_traceback: str = Field(
        description="Raw traceback string preserved for LLM context"
    )


class Hypothesis(BaseModel):
    """A candidate root cause hypothesis generated by the LLM."""

    id: str = Field(description="Hypothesis identifier, e.g. 'h1'")
    description: str = Field(description="Clear description of the root cause")
    probability: float = Field(
        ge=0.0, le=1.0, description="Probability score (0.0 to 1.0)"
    )
    evidence_needed: List[str] = Field(
        default_factory=list,
        description="What evidence would confirm or refute this hypothesis",
    )
    evidence_collected: List[str] = Field(
        default_factory=list,
        description="Evidence gathered so far",
    )
    status: str = Field(
        default="untested",
        description="Current status: untested | confirmed | eliminated",
    )


class ToolResult(BaseModel):
    """Result from running a static analysis tool."""

    tool_name: str = Field(
        description="Tool identifier: ast_analyzer | linter | variable_tracker"
    )
    output: dict = Field(description="Tool-specific output dictionary")
    relevant_to: List[str] = Field(
        default_factory=list,
        description="Hypothesis IDs this evidence applies to",
    )


class AgentAction(BaseModel):
    """An action chosen by the agent during the ReAct loop."""

    action_type: str = Field(
        description="Action type: RUN_TOOL | ASK_USER | CONCLUDE"
    )
    tool_name: Optional[str] = Field(
        default=None, description="Tool to run (if action_type is RUN_TOOL)"
    )
    question: Optional[str] = Field(
        default=None, description="Question for the user (if action_type is ASK_USER)"
    )
    reasoning: str = Field(
        description="Why the agent chose this action"
    )


class DebugResult(BaseModel):
    """Final output of a debugging session."""

    session_id: str = Field(description="Unique session identifier")
    hypotheses: List[Hypothesis] = Field(
        default_factory=list, description="All hypotheses with final probabilities"
    )
    reasoning_chain: List[str] = Field(
        default_factory=list, description="Step-by-step reasoning trace"
    )
    conclusion: str = Field(description="Final root cause explanation")
    confidence: float = Field(
        ge=0.0, le=1.0, description="Confidence score (capped at 0.95)"
    )
    confidence_level: str = Field(
        description="Human-readable confidence: high | medium | low"
    )
    suggested_fix: str = Field(description="Suggested code fix")


class DebugRequest(BaseModel):
    """Incoming request to the /debug endpoint."""

    code: str = Field(description="Python source code to debug")
    traceback: str = Field(description="Raw traceback string from Python")
